// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220622133036_deneme2")]
    partial class deneme2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.kisiler", b =>
                {
                    b.Property<int>("KISI_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KISI_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KISI_SEHIR_ID")
                        .HasColumnType("int");

                    b.Property<string>("KISI_SOYAD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KISI_TELEFON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SEHIR_ID")
                        .HasColumnType("int");

                    b.HasKey("KISI_ID");

                    b.HasIndex("SEHIR_ID");

                    b.ToTable("kisilers");
                });

            modelBuilder.Entity("WebApplication1.Models.sehirler", b =>
                {
                    b.Property<int>("SEHIR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SEHIR_AD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SEHIR_PLAKA_KOD")
                        .HasColumnType("int");

                    b.HasKey("SEHIR_ID");

                    b.ToTable("sehirlers");
                });

            modelBuilder.Entity("WebApplication1.Models.kisiler", b =>
                {
                    b.HasOne("WebApplication1.Models.sehirler", "sehir")
                        .WithMany("kisilers")
                        .HasForeignKey("SEHIR_ID");

                    b.Navigation("sehir");
                });

            modelBuilder.Entity("WebApplication1.Models.sehirler", b =>
                {
                    b.Navigation("kisilers");
                });
#pragma warning restore 612, 618
        }
    }
}
